name: Default
on:
  push: { branches: [ master ] }
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.4.4', '8.10.7']
        cabal: ['3.8.1.0']
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    
    - name: Build and run tests
      run: cabal test

    - name: Publish to Hackage
      if: ${{ fromJSON(env.PUSH_PACKAGES) }}
      run: cabal sdist && cabal upload --username ${{ secrets.HACKAGE_USER }} --password ${{ secrets.HACKAGE_PASS }} dist-newstyle/sdist/*.tar.gz
